config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :skip => [:sessions, :registrations]

    as :user do
        
        get "login" => "devise/sessions#new", :as => :new_user_session
        post "login" => "devise/sessions#create", :as => :user_session
        delete 'signout'  => 'devise/sessions#destroy',   :as => :destroy_user_session
            
    end
    
    root to: 'dashboard#index'

    namespace :api, defaults: {format: 'json'} do
        namespace :v1 do

            resources :appointments

            get 'get_appointment_by_patient_id' => 'appointments#get_appointment_by_patient_id'
            get 'get_appointment_by_id' => 'appointments#get_appointment_by_id'
            get 'get_appointments_by_date' => 'appointments#get_appointments_by_date'

            resources :patients

            get 'get_patient_by_name' => 'patients#get_patient_by_name'
            get 'get_patient_by_name_and_consultation_date' => 'patients#get_patient_by_name_and_consultation_date'
            
        end
    end
    
    namespace :settings do
            
        put 'general/update'

        resources :general
        resources :categories

        get 'user_management/:id/profile' => 'user_management#profile', :as => :user_management_profile
        get 'user_management/:id/edit_profile' => 'user_management#edit_profile', :as => :user_management_edit_profile
        patch 'user_management/:id/update_profile' => 'user_management#update_profile', :as => :user_management_update_profile
        get 'user_management/:id/account_settings' => 'user_management#account_settings', :as => :user_management_account_settings
        patch 'user_management/:id/update_account_settings' => 'user_management#update_account_settings', :as => :user_management_update_account_settings

        resources :user_management

    end

    get '/appointments/history' => 'appointments#history', :as => :appointment_history
    post '/appointments/filter' => 'appointments#filter_appointment'
    resources :appointments
    resources :history
    get '/history/appointment_details/:id' => 'history#appointment_details', :as => :history_appointment_details
    resources :follow_ups
    delete 'patients/attachment_delete/:id' => 'patients#attachment_delete'
    get '/patients/appointment_details/:id' => 'patients#appointment_details', :as => :patient_appointment_details
    resources :patients
    resources :health_maintenance_organizations

    resources :search
    
end

app/controllers/follow_ups_controller.rb
class FollowUpsController < ApplicationController
    
    before_action :get_user
    
    def index
        @follow_ups = Appointment.all  #get_todays_appointments

    end
    
    def new 
        @appointment = Appointment.new
        @appointment.medical_records = medical_records_params
    end
    
    def create
#        render json: appointment_params
        # render json: Patient.get_patient_latest_complete_appointment_by_patient_id(appointment_params[:patient_id])

        appointment_type = "return_visit";

        if check_return_visit_is_present(appointment_params[:consultation_date], appointment_params[:patient_id]).blank?

            if !Appointment.save_follow_up_appointment_main(appointment_params, appointment_type).nil?
                flash[:success] = "Appointment successfully created"
                redirect_to appointments_path(filter: "today")
            end
        else
            flash[:error] = "This patient has already scheduled an appointment for this date."
            redirect_to new_follow_up_path
        end

    end
    
    private

    def medical_records_params
        medical_records = { menarche: "", gravida: 0, para: 0, t: 0, p: 0, a: 0, l: 0, ob_history: "", type: "ob", lmp: "", edc: "", aog: "", chief_complaint: "", history_of_present_illness: "", return_visit: "", diagnosis: "", past_medical_history: "", laboratory_results: "", physical_examinations: ""}

        return medical_records
    end
    
    def check_return_visit_is_present(date, patient_id)
        @appointment = Appointment.where('consultation_date = ? AND patient_id = ?', DateTime.parse(date), patient_id)

        if !@appointment.nil?
            return @appointment
        else
            return nil
        end

    end

    def get_user
        @patients = Patient.get_patient_latest_complete_appointment
    end
     
    def appointment_params
        params.require(:appointment).permit(:appointment_id, :patient_id, :consultation_date, :appointment_type, :systolic, :diastolic, :weight, medical_records: [:menarche, :gravida, :para, :t, :p, :a, :l, :ob_history, :type, :lmp, :edc, :aog, :chief_complaint,              :history_of_present_illness, :return_visit, :record_date, :management, :recommendations, :diagnosis,                            :past_medical_history, :laboratory_results, :physical_examinations])
    end
    
end

app/helpers/follow_up_helper.rb
module FollowUpHelper
end

app/views/follow_ups/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Follow Up</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_path %>">Home</a>
            </li>
            <li class="active">
                <strong>Return Visit</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        <a href="<%= new_follow_up_path %>" class="btn btn-primary pull-right" style="margin: 30px 0 0 0;"><i class="fa fa-plus"></i> Add follow up</a>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        
        <div class="col-lg-12">
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-all">All Appointments</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-today">Today</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-yesterday">Yesterday</a></li>
                </ul>
                <div class="tab-content">
                    <div id="tab-all" class="tab-pane active">
                        <div class="panel-body">
                             <table class="table table-striped table-bordered table-hover " id="tbl-appointments">
                                <thead>
                                    <tr>
                                        <th>Patient ID</th>
                                        <th>Patient Name</th>
                                        <th>Record Date</th>
                                        <th>Complaint</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @follow_ups.each do |follow_up|  %>
                                        <tr class="gradeX">
                                            <td><%= follow_up.patient_id %></td>
                                            <td><%= follow_up.last_name %>, <%= follow_up.first_name %> <%= follow_up.middle_name %></td>
                                            <td><%= format_date(follow_up.consultation_date, "%Y %B %d") %></td>
                                            <td><%= follow_up.complaint %></td>
                                            <td><%= follow_up.status.titlecase %></td>
                                            <td class="center">
                                                <a href="<%= edit_follow_up_path(follow_up.id) %>" class="btn btn-primary btn-xs" data-appointment="<%= follow_up.to_json %>"><i class="fa fa-pencil-square-o"></i></a>
                                            </td>
                                        </tr>
                                    <% end %>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Patient ID</th>
                                        <th>Patient Name</th>
                                        <th>Record Date</th>
                                        <th>Complaint</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div id="tab-today" class="tab-pane">
                        <div class="panel-body">
                            <strong>Today</strong>

                            <p>Thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects
                                and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath </p>

                            <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite
                                sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet.</p>
                        </div>
                    </div>
                    <div id="tab-yesterday" class="tab-pane">
                        <div class="panel-body">
                            <strong>Yesterday</strong>

                            <p>Thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects
                                and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath </p>

                            <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite
                                sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet.</p>
                        </div>
                    </div>
                </div>


            </div>
        </div>
        
    </div>
</div>

app/views/follow_ups/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Return Visit</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_path %>">Home</a>
            </li>
            <li class="active">
                <strong>Return Visit</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <%= form_for @appointment, url: { action: "create" }, :html => { :multipart => true, :class => "wizard-big", :id => "frm-appointment"} do |f| %>
                        <%= render partial: partials[:form][:follow_up], :locals => { :f => f, :title => "New Follow Up" } %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>