config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :skip => [:sessions, :registrations]

    as :user do
        
        get "login" => "devise/sessions#new", :as => :new_user_session
        post "login" => "devise/sessions#create", :as => :user_session
        delete 'signout'  => 'devise/sessions#destroy',   :as => :destroy_user_session
            
    end
    
    root to: 'dashboard#index'

    namespace :api, defaults: {format: 'json'} do
        namespace :v1 do

            resources :appointments

            get 'get_appointment_by_patient_id' => 'appointments#get_appointment_by_patient_id'
            get 'get_appointment_by_id' => 'appointments#get_appointment_by_id'
            get 'get_appointments_by_date' => 'appointments#get_appointments_by_date'

            resources :patients

            get 'get_patient_by_name' => 'patients#get_patient_by_name'
            get 'get_patient_by_name_and_consultation_date' => 'patients#get_patient_by_name_and_consultation_date'
            
        end
    end
    
    namespace :settings do
            
        put 'general/update'

        resources :general
        resources :categories

        get 'user_management/:id/profile' => 'user_management#profile', :as => :user_management_profile
        get 'user_management/:id/edit_profile' => 'user_management#edit_profile', :as => :user_management_edit_profile
        patch 'user_management/:id/update_profile' => 'user_management#update_profile', :as => :user_management_update_profile
        get 'user_management/:id/account_settings' => 'user_management#account_settings', :as => :user_management_account_settings
        patch 'user_management/:id/update_account_settings' => 'user_management#update_account_settings', :as => :user_management_update_account_settings

        resources :user_management

    end

    get '/appointments/history' => 'appointments#history', :as => :appointment_history
    post '/appointments/filter' => 'appointments#filter_appointment'
    resources :appointments
    resources :history
    get '/history/appointment_details/:id' => 'history#appointment_details', :as => :history_appointment_details
    resources :follow_ups
    delete 'patients/attachment_delete/:id' => 'patients#attachment_delete'
    get '/patients/appointment_details/:id' => 'patients#appointment_details', :as => :patient_appointment_details
    resources :patients
    resources :health_maintenance_organizations

    resources :search
    
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController

  include ApplicationHelper

  before_action :check_authorization, :get_appointment_history

  def index
    # render json: @appointment_history
  end

  def appointment_details
    @appointment = Appointment.find(params[:id])

    if @appointment.appointment_type == "return_visit"
      @appointment.medical_records = Appointment.find(@appointment.parent_id).medical_records
    end
    # render json:@appointment
  end

  private

  def get_appointment_history
    if params[:filter].present?
      if params[:filter].has_key?(:date)
        if  params[:filter][:type].to_i == 1
          @appointment_history = Appointment.where(:consultation_date => params[:filter][:date]).order('consultation_date desc')
        elsif params[:filter][:type].to_i == 2
            month = params[:filter][:date].split('/')[0]
            year = params[:filter][:date].split('/')[1]
            @appointment_history = Appointment.where("extract(month  from consultation_date) = ? and extract(year  from consultation_date)  = ?", month, year).order('consultation_date desc')
        else
          year = params[:filter][:date]
          @appointment_history = Appointment.where("extract(year  from consultation_date) = ?", year).order('consultation_date desc')
        end

      else
        start_date = params[:filter][:start].to_date.beginning_of_day
        end_date = params[:filter][:end].to_date.end_of_day
        @appointment_history = Appointment.where(:consultation_date => start_date..end_date).order('consultation_date desc')
      end
    else
        @appointment_history = Appointment.where("consultation_date <= ?", Date.today).order('consultation_date desc')
    end
  end



end

app/helpers/history_helper.rb
module HistoryHelper
end

app/views/history/appointment_details.html.erb
<style>
  .input-group-btn-vertical .bootstrap-touchspin-down {
    margin: -7px 0 0 -1px !important;
  }

  .required {
    color: #ca4440;
  }

  .mp0i {
    margin: 0 !important;
    padding: 0 !important;
  }

  .inline-group label,
  inline-group p {
    display:inline;
  }


  /*.record-container {*/

  /*min-height: 230px;*/
  /*}*/

</style>
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>History Appointment Details</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_url %>">Home</a>
      </li>
      <li>
        <a href="<%= history_path %>">History</a>
      </li>
      <li class="active">
        <strong>History Appointment Details</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
    <a href="<%= history_index_path %>" class="btn btn-info btn-sm pull-right" style="margin: 32px -5px 0 0;"><i class="fa fa-arrow-left"></i> Back to History</a>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">

        <div class="col-lg-12">
          <div class="ibox float-e-margins">
            <div class="ibox-title">
              <h5>Medical Record: </h5>
            </div>
            <div class="ibox-content">
              <div class="row">
                <div class="col-md-12">
                  <div class="row record-container">
                    <div class="col-md-12">
                      <div class="form-group">

                        <div class="inline-group col-xs-3" style="white-space:nowrap">
                          <p><label class="control-label">Type: </label>
                            <%= @appointment.medical_records["type"].titlecase %></p>
                        </div>

                        <div class="inline-group col-xs-3" style="white-space:nowrap" >
                          <p><label class="control-label">LMP: </label>
                            <%= @appointment.medical_records["lmp"] %></p>
                        </div>

                        <div class="inline-group col-xs-3" style="white-space:nowrap">
                          <p><label class="control-label">EDC: </label>
                            <%= @appointment.medical_records["edc"] %></p>
                        </div>

                        <div class="inline-group col-xs-3" style="white-space:nowrap">
                          <p><label class="control-label">Record Date: </label>
                            <%= @appointment.record_date %></p>
                        </div>

                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group">

                        <div class="inline-group col-xs-3" style="white-space:nowrap">
                          <p><label class="control-label">Menarche: </label>
                            <%= @appointment.medical_records["menarche"] %></p>
                        </div>

                        <div class="inline-group col-xs-2" style="white-space:nowrap">
                          <p><label class="control-label">Gravida: </label>
                            <%= @appointment.medical_records["gravida"] %></p>
                        </div>

                        <div class="inline-group col-xs-1" style="white-space:nowrap">
                          <p><label class="control-label">Para: </label>
                            <%= @appointment.medical_records["para"] %></p>
                        </div>

                        <div class="inline-group col-xs-1" style="white-space:nowrap">
                          <p><label class="control-label">T: </label>
                            <%= @appointment.medical_records["t"] %></p>
                        </div>

                        <div class="inline-group col-xs-1" style="white-space:nowrap">
                          <p><label class="control-label">P: </label>
                            <%= @appointment.medical_records["p"] %></p>
                        </div>

                        <div class="inline-group col-xs-1" style="white-space:nowrap">
                          <p><label class="control-label">A: </label>
                            <%= @appointment.medical_records["a"] %></p>
                        </div>

                        <div class="inline-group col-xs-1" style="white-space:nowrap">
                          <p> <label class="control-label">L: </label>
                            <%= @appointment.medical_records["l"] %></p>
                        </div>

                      </div>
                    </div>

                  </div>

                  <div class="hr-line-dashed"></div>
                  <div class="well">
                    <div class="row">

                      <div class="col-md-6">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Chief Complaint : </label>
                                <p><%= @appointment.medical_records['chief_complaint'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">History of Present Illness: </label>
                                <p><%= @appointment.medical_records['history_of_present_illness'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Ob-Gyne History: </label>
                                <p><%= @appointment.medical_records['ob_history'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Diagnosis: </label>
                                <p><%= @appointment.medical_records['diagnosis'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Past Medical History: </label>
                                <p><%= @appointment.medical_records['past_medical_history'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Laboratory Results: </label>
                                <p><%= @appointment.medical_records['laboratory_results'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Physical Examinations: </label>
                                <p><%= @appointment.medical_records['physical_examinations'] %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Management: </label>
                                <p><%= @appointment.management %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-md-12">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <div class="inline-group col-xs-12">
                                <label class="control-label">Recomendations: </label>
                                <p><%= @appointment.recommendations  %></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/history/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-4">
        <h2>Appointments</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_path %>">Home</a>
            </li>
            <li class="active">
                <strong>History</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-8">
      <form action="<%= history_index_path %>" method="get">
      <div class="col-md-12">
        <div class="col-md-5">
          <div class="input-group pull-right" style="margin: 30px 0 0 0;" >
            <select id="select-filter-type" data-placeholder="" name="filter[type]" class="chosen-select" tabindex="2" style=" width: 120px;">
              <option value="0">Range</option>
              <option value="1">Day</option>
              <option value="2">Month</option>
              <option value="3">Year</option>
            </select>
          </div>
          </div>

        <div class="col-md-5">
          <div class="form-group" id="range">
            <div class="input-daterange input-group" id="datepicker" style="margin: 30px 0 0 0;">
              <input type="text" class="input-sm form-control" name="filter[start]" value="" required/>
              <span class="input-group-addon">to</span>
              <input type="text" class="input-sm form-control" name="filter[end]" value="" required/>
            </div>
          </div>

            <div class="form-group hidden" id="date" style="margin: 30px 0 0 0;">
              <div class="input-group date">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control" name="filter[date]" disabled value="" required>
              </div>
          </div>

          </div>
        <div class="col-md-2 mp0i">
        <button type="submit" class="btn btn-info" style="margin: 30px 0 0 0;"><i class="fa fa-filter"></i> Filter</button>
          </div>
        </form>
        </div>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">

        <div class="ibox-content">
          <% if params[:filter].present? %>
            <h3>Appointment History List<span class="semi-bold"> (<%=  params[:filter].has_key?(:date) ? params[:filter][:date] : "#{  params[:filter][:start] +" - "+ params[:filter][:end]}" %>)</span></h3><br \>
          <% else %>
            <h3>Appointment History List<span class="semi-bold"></span></h3><br \>
          <% end %>
          <div class="">

          </div>
          <table class="table table-striped table-bordered table-hover " id="tbl-appointments">
            <thead>
            <tr>
              <th>Patient Name</th>
              <th>Record Date</th>
              <th>Complaint</th>
              <th>Type</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% @appointment_history.each do |appointment|  %>
                <tr class="gradeX">
                  <td><%= get_patient_by_id(appointment.patient_id) %></td>
                  <td><%= format_date(appointment.consultation_date, "%Y %B %d") %></td>
                  <td><%= appointment.medical_records['chief_complaint'] %></td>
                  <td><%= appointment.appointment_type.humanize.titlecase %></td>
                  <td class="center">
                   <%= appointment.status.humanize.titlecase %>
                  </td>
                  <td>
                    <a href="<%= history_appointment_details_path(appointment.id) %>" class="btn btn-default btn-xs">View Details</a>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>