config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :skip => [:sessions, :registrations]

    as :user do
        
        get "login" => "devise/sessions#new", :as => :new_user_session
        post "login" => "devise/sessions#create", :as => :user_session
        delete 'signout'  => 'devise/sessions#destroy',   :as => :destroy_user_session
            
    end
    
    root to: 'dashboard#index'

    namespace :api, defaults: {format: 'json'} do
        namespace :v1 do

            resources :appointments

            get 'get_appointment_by_patient_id' => 'appointments#get_appointment_by_patient_id'
            get 'get_appointment_by_id' => 'appointments#get_appointment_by_id'
            get 'get_appointments_by_date' => 'appointments#get_appointments_by_date'

            resources :patients

            get 'get_patient_by_name' => 'patients#get_patient_by_name'
            get 'get_patient_by_name_and_consultation_date' => 'patients#get_patient_by_name_and_consultation_date'
            
        end
    end
    
    namespace :settings do
            
        put 'general/update'

        resources :general
        resources :categories

        get 'user_management/:id/profile' => 'user_management#profile', :as => :user_management_profile
        get 'user_management/:id/edit_profile' => 'user_management#edit_profile', :as => :user_management_edit_profile
        patch 'user_management/:id/update_profile' => 'user_management#update_profile', :as => :user_management_update_profile
        get 'user_management/:id/account_settings' => 'user_management#account_settings', :as => :user_management_account_settings
        patch 'user_management/:id/update_account_settings' => 'user_management#update_account_settings', :as => :user_management_update_account_settings

        resources :user_management

    end

    get '/appointments/history' => 'appointments#history', :as => :appointment_history
    post '/appointments/filter' => 'appointments#filter_appointment'
    resources :appointments
    resources :history
    get '/history/appointment_details/:id' => 'history#appointment_details', :as => :history_appointment_details
    resources :follow_ups
    delete 'patients/attachment_delete/:id' => 'patients#attachment_delete'
    get '/patients/appointment_details/:id' => 'patients#appointment_details', :as => :patient_appointment_details
    resources :patients
    resources :health_maintenance_organizations

    resources :search
    
end

app/models/setting.rb
class Setting < ActiveRecord::Base

    has_attached_file :logo,
        # :styles => { :large => "1920x900#", :medium => "600x600>", :small => "300x300", :thumb => "100x100>" },
        :url => "/system/:class/:attachment/:id/:style/:basename.:extension",
        :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"

    # , :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

    serialize :body, JSON

end

app/controllers/settings/general_controller.rb
class Settings::GeneralController < ApplicationController
    
    include ApplicationHelper
    before_action :authenticate_user!
    before_action :check_authorization
    
    def index
        @setting = Setting.first
    end
    
    def update
    
        @setting = Setting.first
        
        if @setting.update(settings_params)
            flash[:success] = "Settings successfully updated."
            redirect_to settings_general_index_path
        else 
            flash[:error] = @setting.errors.full_messages.first
            redirect_to settings_general_index_path
        end
        
    end
    
    private
    
    def settings_params
        params.require(:setting).permit(:name, :logo, body: [:app_name, :app_initials, :admin_email, :app_description])
    end
    
end

app/controllers/settings/health_maintenance_organizations_controller.rb
class Settings::HealthMaintenanceOrganizationsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  before_action :check_authorization, :get_hmo_list

  def index
    @hmo = HealthMaintenanceOrganization.new
  end

  def create

    @hmo = HealthMaintenanceOrganization.new(hmo_params)

    if @hmo.save
      flash[:success] = "Category successfully created."
      redirect_to settings_health_maintenance_organizations_path
    else
      flash[:error] = @hmo.errors.full_messages.first
      redirect_to settings_health_maintenance_organizations_path
    end

  end

  def edit
    @hmo = HealthMaintenanceOrganization.find(params[:id])
  end

  def update
    @hmo = HealthMaintenanceOrganization.find(params[:id])

    if @hmo.update(hmo_params)
      flash[:success] = "Category successfully created."
      redirect_to edit_settings_health_maintenance_organization_path(@hmo.id)
    else
      flash[:success] = "Category successfully created."
      redirect_to edit_settings_health_maintenance_organization_path(@hmo.id)
    end
  end

  def destroy
    @hmo = HealthMaintenanceOrganization.find(params[:id])

    if @hmo.destroy
      flash[:success] = "Category successfully deleted."
      redirect_to settings_health_maintenance_organizations_path
    end
  end

  private

  def get_hmo_list
    @hmo_list = HealthMaintenanceOrganization.all
  end

  def hmo_params
    params.require(:hmo).permit(:name, :description)
  end

end

app/controllers/settings/user_management_controller.rb
class Settings::UserManagementController < ApplicationController

    include ApplicationHelper
    
    before_action :authenticate_user!
    before_action :check_authorization
    
    before_action :get_all_users
    before_action :get_all_countries
    
    def index
#        render json: params
    end
    
    def new
        @user = User.new
    end

    def create

      @user = User.new(user_params)

      if @user.save
          flash[:success] = "User successfully created."
          redirect_to settings_user_management_index_path
      else
          render 'new'
      end 

    end

    def edit
      @user = User.find(params[:id])
    end
    
    def update

      @user = User.find(params[:id])
        
      if @user.update(user_params)
          flash[:success] = "User successfully updated."
          redirect_to edit_settings_user_management_path(@user.id)
      else 
          flash[:error] =  @user.errors.full_messages.first
          redirect_to edit_settings_user_management_path(@user.id)
      end
    end

    def destroy

        @user = User.find(params[:id])

        if @user.destroy
            flash[:success] = "User successfully deleted."
            redirect_to settings_user_management_index_path
        end
    end

    def profile
        @user = User.find(params[:id])
    end

    def edit_profile
        @user = User.find(params[:id])
    end

    def update_profile

        @user = User.find(params[:id])

        if @user.update(user_params)
            flash[:success] = "User successfully updated."
            redirect_to settings_user_management_profile_path(params[:id])
        else
            flash[:error] = @user.errors.full_messages.first
            redirect_to settings_user_management_profile_path(params[:id])
        end

    end

    def account_settings
        @user = User.find(params[:id])
    end

    def update_account_settings

        @user = User.find(params[:id])

        if @user.update(user_params)
            flash[:success] = "Account settings successfully updated."
            redirect_to settings_user_management_account_settings_path(params[:id])
        else
            flash[:error] = @user.errors.full_messages.first
            redirect_to settings_user_management_account_settings_path(params[:id])
        end
    end

    private
    
    def get_all_users
        @users = User.where.not(role: 0)
    end
    
    def get_all_countries
        @countries = CS.get
    end
    
    def user_params
        if !params[:user][:password].blank?
            params.require(:user).permit(:email, :username, :first_name, :last_name, :role, :gender, :birth_date, :address, :country, :postal_code, :phone_number, :status, :password, :password_confirmation, :avatar, :password, :password_confirmation)
        else 
            params.require(:user).permit(:email, :username, :first_name, :last_name, :role, :gender, :birth_date, :address, :country, :postal_code, :phone_number, :status, :avatar)
        end
    end
    
end

app/helpers/settings/general_helper.rb
module Settings::GeneralHelper
end

app/helpers/settings/health_maintenance_organizations_helper.rb
module Settings::HealthMaintenanceOrganizationsHelper
end

app/helpers/settings/users_helper.rb
module Settings::UsersHelper
end

app/views/settings/user_management/account_settings.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Account Settings</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_url %>">Home</a>
      </li>
      <li>
        <a>Settings</a>
      </li>
      <li class="active">
        <strong>Account Settings</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <table class="table no-more-tables m-t-20 m-l-20 m-b-30" style="margin-top:20px;">
            <thead style="display:none">
            <tr>
              <th style="width:9%">Name</th>
              <th style="width:22%">Username</th>
              <th style="width:6%">Contact</th>
              <th style="width:1%"> </th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td class="v-align-middle bold text-primary">Name</td>
              <td class="v-align-middle"><span class="muted"><%= @user.first_name %> <%= @user.last_name %></span> </td>
              <td><span class="muted bold" id="edit-name" style="cursor:pointer;">Edit</span> </td>
              <td class="v-align-middle"></td>
            </tr>
            <tr>
              <td class="v-align-middle bold text-primary">Username</td>
              <td class="v-align-middle"><span class="muted"><%= @user.username %></span> </td>
              <td><span class="muted bold" id="edit-username" style="cursor:pointer;">Edit</span> </td>
              <td class="v-align-middle"></td>
            </tr>
            <tr>
              <td class="v-align-middle bold text-primary">Contact</td>
              <td class="v-align-middle"><span class="muted"><%= @user.email %></span> </td>
              <td><span class="muted bold" id="edit-contact" style="cursor:pointer;">Edit</span> </td>
              <td class="v-align-middle"></td>
            </tr>
            <tr>
              <td class="v-align-middle bold text-primary">Password</td>
              <td class="v-align-middle"><span class="muted">Update you current password.</span> </td>
              <td><span class="muted bold" id="edit-password" style="cursor:pointer;">Edit</span> </td>
              <td class="v-align-middle"></td>
            </tr>
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="mdl-edit-account" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <%= form_for @user, url: { action: "update_account_settings" }, :html => { :multipart => true, :class => "form-horizontal", :id => "form-condensed" } do |f| %>
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <br>
            <h4 id="myModalLabel" class="semi-bold text-center">Account Information</h4>
            <p class="no-margin text-center"">Update your <span id="spn-edit-name" class="semi-bold">name</span></p>
            <br>

            <div id="dv-name-container" class="hidden">
              <div class="row">
                <div class="col-md-6">
                  <%= f.text_field :first_name, autofocus: true, class: "form-control", placeholder: "First Name", required: true %>
                </div>
                <div class="col-md-6">
                  <%= f.text_field :last_name, autofocus: true, class: "form-control", placeholder: "Last Name", required: true %>
                </div>
              </div>
            </div>
            <div id="dv-username-container" class="hidden">
              <div class="row form-row">
                <div class="col-md-12">
                  <%= f.text_field :username, autofocus: true, class: "form-control", placeholder: "First Name", required: true %>
                </div>
              </div>
            </div>
            <div id="dv-contact-container" class="hidden">
              <div class="row form-row">
                <div class="col-md-12">
                  <%= f.text_field :email, autofocus: true, class: "form-control", placeholder: "First Name", required: true %>
                </div>
              </div>
            </div>
            <div id="dv-password-container" class="hidden">
              <div class="row form-row">
                <div class="col-md-6">
                  <%= f.password_field :password, autofocus: true, class: "form-control", placeholder: "New Password", required: true %>
                </div>
                <div class="col-md-6">
                  <%= f.password_field :password_confirmation, autofocus: true, class: "form-control", placeholder: "Confirm Password", required: true %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-info">Update</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/settings/user_management/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edit User</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_url %>">Home</a>
        </li>
        <li>
            <a>Settings</a>
        </li>
        <li class="active">
            <strong>Edit User</strong>
        </li>
    </ol>
</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Note: <small>Labels with * are required</small></h5>
            </div>
            <div class="ibox-content">
                <%= form_for @user, url: { action: "update" }, :html => { :multipart => true, :class => "form-horizontal" } do |f| %>
                    <%= render partial: partials[:form][:user], :locals => { :f => f, :title => "Edit User" } %>
                <% end %>
            </div>
        </div>
    </div>
 
</div>
</div>

app/views/settings/user_management/edit_profile.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Edit Profile</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_url %>">Home</a>
      </li>
      <li>
        <a>Settings</a>
      </li>
      <li class="active">
        <strong>Edit Profile</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
            <h4>Profile <span class="semi-bold">Picture</span></h4>
            <div class="row">
              <div class="col-md-6">
                <div class="image-avatar-crop">
                  <% if @user.avatar.present? %>
                      <img src="<%= @user.avatar.url(:original) %>">
                  <% else %>
                      <img src="<%= image_path('empty-state-avatar-1.png') %>">
                  <% end %>
                </div>
              </div>
              <div class="col-md-6">
                <h4>Preview <span class="semi-bold">Avatar</span></h4>
                <div class="col-md-12 mp0i">
                  <div class="img-avatar-preview img-avatar-preview-sm"></div>
                  <p>Recomended photo size: 200 × 200</p>
                </div>
                <div class="col-md-12 mp0i">
                  <%= form_for @user, url: { action: "update_profile" }, :html => { :multipart => true, :class => "", :id => "frm-user-avatar" } do |f| %>

                      <%= f.hidden_field :avatar, class: "hide" %>

                      <label title="Upload image file" for="inputImage" class="btn btn-white ">
                        <input type="file" class="hide" id="inputImage" accept="image/*">
                        <i class="fa fa-cloud-upload" aria-hidden="true"></i> Upload your photo
                      </label>
                      <button type="button" id="btn-crop" class="btn btn-info">Set as Profile Picture</button>

                  <% end %>
                </div>
                <div class="col-md-12 mp0i">
                  <h4>Crop Tools</h4>
                  <div class="dv-btn-command-container">
                    <div class="btn-group">
                      <button class="btn btn-white btn-sm btn-small" id="zoomIn" type="button"><i class="fa fa-search-plus" aria-hidden="true"></i></button>
                      <button class="btn btn-white btn-sm btn-small" id="zoomOut" type="button"><i class="fa fa-search-minus" aria-hidden="true"></i></button>
                      <button class="btn btn-white btn-sm btn-small" id="rotateRight" type="button"><i class="fa fa-undo"></i></button>
                      <button class="btn btn-white btn-sm btn-small" id="rotateLeft" type="button"><i class="fa fa-repeat"></i></button>
                      <button class="btn btn-white btn-sm btn-small" id="btn-reload" type="button"><i class="fa fa-refresh" aria-hidden="true"></i></button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">

        <div class="ibox-content">
          <h4>Personal Information</h4>
          <div class="row">
            <div class="col-md-12">
              <%= form_for @user, url: { action: "update_profile" }, :html => { :multipart => true, :class => "form-horizontal", :id => "form-condensed" } do |f| %>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group" >
                        <div class="col-md-5">
                          <label class="control-label">Gender *</label>
                          <%= f.select(:gender, options_for_select(User.genders.collect{ |k, v| [k.humanize.titlecase, k]}, @user.gender), {}, { :class => 'select2_demo_1 form-control' }) %>
                        </div>
                        <div class="col-md-7">
                          <div class="form-group" id="data_3" style="margin-bottom: 0 !important">
                            <label class="control-label">Birth Date *</label>
                            <div class="input-group date">
                              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                              <%= f.text_field :birth_date, value: format_date(@user.birth_date, "%d/%m/%Y"), autofocus: true, class: "form-control", style: "width: 97.5%;",required: true %>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-12">
                          <label class="control-label">Address *</label>
                          <%= f.text_field :address, autofocus: true, class: "form-control", required: true %>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-8">
                          <label class="control-label">Country *</label>
                          <%= f.select(:country, options_for_select(@countries.collect{ |k, v| [v, v]}), {}, { :class => 'select2_demo_1 form-control' }) %>
                        </div>
                        <div class="col-md-4">
                          <label class="control-label">Postal *</label>
                          <%= f.text_field :postal_code, autofocus: true, class: "form-control postal-code", required: true, data: { mask: "99999" } %>
                        </div>
                      </div>
                      <div class="form-group">
                      <div class="col-md-12">
                        <label class="control-label">Phone Number *</label>
                        <%= f.text_field :phone_number, autofocus: true, class: "form-control phone", required: true, data: { mask: "(99) 99999-9999" } %>
                      </div>
                    </div>
                    </div>
                  </div>
                  <div class="hr-line-dashed"></div>
                  <div class="form-group">
                    <div class="col-md-6 pull-right">
                      <a href="<%= settings_user_management_index_path %>" class="btn btn-white pull-right">Cancel</a>
                      <button class="btn btn-success pull-right" type="submit" style="margin: 0 5px 0 0px;">Update</button>
                    </div>
                  </div>
               <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/settings/user_management/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>User Management</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_path %>">Home</a>
            </li>
            <li>
                <a>Settings</a>
            </li>
            <li class="active">
                <strong>User Management</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
        <a href="<%= new_settings_user_management_path %>" class="btn btn-success pull-right" style="margin: 30px 0 0 0;"><i class="fa fa-plus"></i> Add new user</a>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
<div class="col-lg-12">
<div class="ibox float-e-margins">

<div class="ibox-content">
<h3>User <span class="semi-bold">List</span></h3><br \>
<div class="">
    
</div>
<table class="table table-striped table-bordered table-hover " id="editable">
    <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Name</th>
            <th>Status</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user|  %>
            <tr class="gradeX">
                <td><%= user.username %></td>
                <td><%= user.email %></td>
                <td><%= user.first_name %> <%= user.last_name %></td>
                <td class="center"><%= user.status.titlecase %></td>
                <td class="center"><%= user.role.titlecase %></td>
                <td class="center">
                    <a href="<%= edit_settings_user_management_path(user.id) %>" class="btn btn-primary btn-xs" ><i class="fa fa-pencil-square-o"></i></a>
                    <a href="javascript:void(0);" class="btn btn-success btn-xs" ><i class="fa fa-sign-in"></i></a>
                    <a href="javascript:void(0);" class="btn btn-danger btn-xs" id="btn-delete" data-user="<%= user.to_json  %>"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        <% end %>
    </tbody>
    <tfoot>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Name</th>
            <th>Status</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
    </tfoot>
</table>

</div>
</div>
</div>
</div>
</div>

<div id="mdl-delete" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirm Delete</h4>
      </div>
      <div class="modal-body">
          <p>Are you sure you want to delete <span id="spn-name">ascc</span>?</p>
      </div>
      <div class="modal-footer">
          <%= form_tag({}, {:method => :delete, :id => "frm-delete"}) do %>
              <button type="submit" class="btn btn-danger" >Delete</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/settings/user_management/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Create User</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= root_url %>">Home</a>
        </li>
        <li>
            <a>Settings</a>
        </li>
        <li class="active">
            <strong>Create User</strong>
        </li>
    </ol>
</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Note: <small>Labels with * are required</small></h5>
            </div>
            <div class="ibox-content">
                <%= form_for @user, url: { action: "create" }, :html => { :multipart => true, :class => "form-horizontal" } do |f| %>
                    <%= render partial: partials[:form][:user], :locals => { :f => f, :title => "New User" } %>
                <% end %>
            </div>
        </div>
    </div>
</div>
</div>

app/views/settings/user_management/profile.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>My Profile</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= root_url %>">Home</a>
      </li>
      <li>
        <a>Settings</a>
      </li>
      <li class="active">
        <strong>My Profile</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
    <a href="<%= settings_user_management_edit_profile_path %>" class="btn btn-success pull-right" style="margin: 30px 0 0 0;"><i class="fa fa-pencil-square-o"></i> Edit Personal Information</a>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <div class="row">
            <div class="col-md-2">
              <div class="dv-user-info-wrapper">
                <div class="dv-user-profile-pic">
                  <% if @user.avatar.present? %>
                      <img class="img-circle" src="<%= @user.avatar.url(:original) %>"  alt="" data-src="<%= @user.avatar.url(:original) %>" data-src-retina="<%= @user.avatar.url(:medium) %>" width="150" height="150" />
                  <% else %>
                      <img class="img-circle" src="<%= image_path('empty-state-avatar-1.png') %>" width="150" height="150">
                  <% end %>
                </div>
              </div>
            </div>
            <div class="col-md-10">
            <div class="dv-container-personal-info">
              <div class="row-fluid">
                <address>
                  <strong><%= @user.first_name %> <%= @user.last_name %></strong><br>
                  <abbr title="Email">Email: </abbr> <a href="#"><%= @user.email %></a><br>
                  <abbr title="Phone">Birthdate:</abbr> <%= format_date(@user.birth_date, "%Y %B %d") %>
                </address>
                <address class="margin-bottom-20 margin-top-10">
                  <strong><%= @user.country %></strong><br>
                  <abbr title="Address">Address:</abbr> <%= @user.address %>, <%= @user.postal_code %><br>
                  <abbr title="Phone">Phone:</abbr> <%= @user.phone_number %>
                </address>
              </div>
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>