config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, :skip => [:sessions, :registrations]

    as :user do
        
        get "login" => "devise/sessions#new", :as => :new_user_session
        post "login" => "devise/sessions#create", :as => :user_session
        delete 'signout'  => 'devise/sessions#destroy',   :as => :destroy_user_session
            
    end
    
    root to: 'dashboard#index'

    namespace :api, defaults: {format: 'json'} do
        namespace :v1 do

            resources :appointments

            get 'get_appointment_by_patient_id' => 'appointments#get_appointment_by_patient_id'
            get 'get_appointment_by_id' => 'appointments#get_appointment_by_id'
            get 'get_appointments_by_date' => 'appointments#get_appointments_by_date'

            resources :patients

            get 'get_patient_by_name' => 'patients#get_patient_by_name'
            get 'get_patient_by_name_and_consultation_date' => 'patients#get_patient_by_name_and_consultation_date'
            
        end
    end
    
    namespace :settings do
            
        put 'general/update'

        resources :general
        resources :categories

        get 'user_management/:id/profile' => 'user_management#profile', :as => :user_management_profile
        get 'user_management/:id/edit_profile' => 'user_management#edit_profile', :as => :user_management_edit_profile
        patch 'user_management/:id/update_profile' => 'user_management#update_profile', :as => :user_management_update_profile
        get 'user_management/:id/account_settings' => 'user_management#account_settings', :as => :user_management_account_settings
        patch 'user_management/:id/update_account_settings' => 'user_management#update_account_settings', :as => :user_management_update_account_settings

        resources :user_management

    end

    get '/appointments/history' => 'appointments#history', :as => :appointment_history
    post '/appointments/filter' => 'appointments#filter_appointment'
    resources :appointments
    resources :history
    get '/history/appointment_details/:id' => 'history#appointment_details', :as => :history_appointment_details
    resources :follow_ups
    delete 'patients/attachment_delete/:id' => 'patients#attachment_delete'
    get '/patients/appointment_details/:id' => 'patients#appointment_details', :as => :patient_appointment_details
    resources :patients
    resources :health_maintenance_organizations

    resources :search
    
end

app/views/layouts/_footer.html.erb
<div class="footer" style="min-height: 45px;">
    <!--<div class="pull-right">-->
        <!--Example text-->
    <!--</div>-->
    <!--<div>-->
        <!--<strong>Copyright</strong> Example Company &copy; 2014-2015-->
    <!--</div>-->
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">

          <li class="nav-header">
            <div class="dropdown profile-element">
                  <span>
                    <% if get_current_user(current_user.id).avatar.present? %>
                        <img class="img-circle" src="<%=  get_current_user(current_user.id).avatar.url(:original) %>"  alt="" data-src="<%= get_current_user(current_user.id).avatar.url(:original) %>" data-src-retina="<%=  get_current_user(current_user.id).avatar.url(:medium) %>" width="50" height="50" />
                    <% else %>
                        <img alt="image" class="img-circle" src="<%= image_path('empty-state-avatar-1.png') %>"  width="50" height="50" style="background:white;"/>
                    <% end %>
                  </span>
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="clear">
                        <span class="block m-t-xs">
                            <strong class="font-bold"><%= current_user.first_name %> <%= current_user.last_name %></strong>
                        </span> <span class="text-muted text-xs block"><%= current_user.role.humanize.titlecase %> <b class="caret"></b></span>
                    </span>
                  </a>
              <ul class="dropdown-menu animated fadeInRight m-t-xs">
                <li><a href="<%= settings_user_management_profile_path(current_user.id) %>"><i class="fa fa-user fa-fw"></i> My Profile</a>
                </li>
                <li><a href="<%= settings_user_management_account_settings_path(current_user.id) %>"><i class="fa fa-cogs fa-fw"></i> Account Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="" class="btn-signout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
              </ul>
            </div>
            <div class="logo-element" style="min-height: 61px;">

            </div>
          </li>
            
            <li class="<%= is_active_controller('dashboard') %>">
                <%= link_to root_path do %>
                    <i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.metrics">Dashboard</span>
                <% end %>
            </li>

            <li class="<%= is_active_controller('appointments') %>">
              <%= link_to appointments_path(filter: 'today') do %>
                  <i class="fa fa-calendar"></i> <span class="nav-label" data-i18n="nav.metrics">Appointments</span>
              <% end %>
            </li>

            <li class="<%= is_active_controller('patients') %>">
                <%= link_to patients_path do %>
                    <i class="fa fa-users"></i> <span class="nav-label" data-i18n="nav.metrics">Patients</span>
                <% end %>
            </li>

            <li class="<%= is_active_controller('history') %>">
                <%= link_to history_index_path do %>
                    <i class="fa fa-history"></i> <span class="nav-label" data-i18n="nav.metrics">History</span>
                <% end %>
            </li>

            <% if super_and_admin_roles %>
              <li class="<%= is_active_controller('health_maintenance_organizations') %>">
                <%= link_to health_maintenance_organizations_path do %>
                    <i class="fa fa-medkit"></i> <span class="nav-label" data-i18n="nav.metrics">HMO</span>
                <% end %>
              </li>
            <% end %>
            
            <% if super_and_admin_roles %>
                <li class="<%= is_active_path('settings') %>">
                    <a href=""><i class="fa fa-cogs"></i> <span class="nav-label" data-i18n="nav.dashboard">Settings</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse <%= is_active_controller('dashboards') %>">
                        <li><%= link_to "General", settings_general_index_path %></li>
                        <li><%= link_to "User Management", settings_user_management_index_path %></li>
                    </ul>
                </li>
            <% end %>
            
        </ul>

    </div>
</nav>


app/views/layouts/_skinconfig.html.erb
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-setttings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                    <span>
                        Collapse menu
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Fixed sidebar
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Top navbar
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Top navbar v.2
                        <br/>
                        <small>*Primary layout</small>
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar2" class="onoffswitch-checkbox" id="fixednavbar2">
                        <label class="onoffswitch-label" for="fixednavbar2">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Boxed layout
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                    <span>
                        Fixed footer
                    </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                    <span class="skin-name ">
                         <a href="#" class="s-skin-0">
                             Default
                         </a>
                    </span>
            </div>
            <div class="setings-item blue-skin">
                    <span class="skin-name ">
                        <a href="#" class="s-skin-1">
                            Blue light
                        </a>
                    </span>
            </div>
            <div class="setings-item yellow-skin">
                    <span class="skin-name ">
                        <a href="#" class="s-skin-3">
                            Yellow/Purple
                        </a>
                    </span>
            </div>
            <div class="setings-item ultra-skin">
                    <span class="skin-name ">
                        <a target="_blank" href="md_skin/" class="md-skin">
                            Material Design
                        </a>
                    </span>
            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">
// Config box

// Enable/disable fixed top navbar
$('#fixednavbar').click(function (){
    if ($('#fixednavbar').is(':checked')){
        $(".navbar-static-top").removeClass('navbar-static-top').addClass('navbar-fixed-top');
        $("body").removeClass('boxed-layout');
        $("body").addClass('fixed-nav');
        $('#boxedlayout').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'on');
        }
    } else{
        $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
        $("body").removeClass('fixed-nav');
        $("body").removeClass('fixed-nav-basic');
        $('#fixednavbar2').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'off');
        }
    }
});

// Enable/disable fixed top navbar
$('#fixednavbar2').click(function (){
    if ($('#fixednavbar2').is(':checked')){
        $(".navbar-static-top").removeClass('navbar-static-top').addClass('navbar-fixed-top');
        $("body").removeClass('boxed-layout');
        $("body").addClass('fixed-nav').addClass('fixed-nav-basic');
        $('#boxedlayout').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'on');
        }
    } else {
        $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
        $("body").removeClass('fixed-nav').removeClass('fixed-nav-basic');
        $('#fixednavbar').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'off');
        }
        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'off');
        }
    }
});

// Enable/disable fixed sidebar
$('#fixedsidebar').click(function (){
    if ($('#fixedsidebar').is(':checked')){
        $("body").addClass('fixed-sidebar');
        $('.sidebar-collapse').slimScroll({
            height: '100%',
            railOpacity: 0.9
        });

        if (localStorageSupport){
            localStorage.setItem("fixedsidebar",'on');
        }
    } else{
        $('.sidebar-collapse').slimscroll({destroy: true});
        $('.sidebar-collapse').attr('style', '');
        $("body").removeClass('fixed-sidebar');

        if (localStorageSupport){
            localStorage.setItem("fixedsidebar",'off');
        }
    }
});

// Enable/disable collapse menu
$('#collapsemenu').click(function (){
    if ($('#collapsemenu').is(':checked')){
        $("body").addClass('mini-navbar');
        SmoothlyMenu();

        if (localStorageSupport){
            localStorage.setItem("collapse_menu",'on');
        }

    } else{
        $("body").removeClass('mini-navbar');
        SmoothlyMenu();

        if (localStorageSupport){
            localStorage.setItem("collapse_menu",'off');
        }
    }
});

// Enable/disable boxed layout
$('#boxedlayout').click(function (){
    if ($('#boxedlayout').is(':checked')){
        $("body").addClass('boxed-layout');
        $('#fixednavbar').prop('checked', false);
        $('#fixednavbar2').prop('checked', false);
        $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
        $("body").removeClass('fixed-nav');
        $("body").removeClass('fixed-nav-basic');
        $(".footer").removeClass('fixed');
        $('#fixedfooter').prop('checked', false);

        if (localStorageSupport){
            localStorage.setItem("fixednavbar",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixednavbar2",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixedfooter",'off');
        }


        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'on');
        }
    } else{
        $("body").removeClass('boxed-layout');

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }
    }
});

// Enable/disable fixed footer
$('#fixedfooter').click(function (){
    if ($('#fixedfooter').is(':checked')){
        $('#boxedlayout').prop('checked', false);
        $("body").removeClass('boxed-layout');
        $(".footer").addClass('fixed');

        if (localStorageSupport){
            localStorage.setItem("boxedlayout",'off');
        }

        if (localStorageSupport){
            localStorage.setItem("fixedfooter",'on');
        }
    } else{
        $(".footer").removeClass('fixed');

        if (localStorageSupport){
            localStorage.setItem("fixedfooter",'off');
        }
    }
});

// SKIN Select
$('.spin-icon').click(function (){
    $(".theme-config-box").toggleClass("show");
});

// Default skin
$('.s-skin-0').click(function (){
    $("body").removeClass("skin-1");
    $("body").removeClass("skin-2");
    $("body").removeClass("skin-3");
});

// Blue skin
$('.s-skin-1').click(function (){
    $("body").removeClass("skin-2");
    $("body").removeClass("skin-3");
    $("body").addClass("skin-1");
});

// Inspinia ultra skin
$('.s-skin-2').click(function (){
    $("body").removeClass("skin-1");
    $("body").removeClass("skin-3");
    $("body").addClass("skin-2");
});

// Yellow skin
$('.s-skin-3').click(function (){
    $("body").removeClass("skin-1");
    $("body").removeClass("skin-2");
    $("body").addClass("skin-3");
});

if (localStorageSupport){
    var collapse = localStorage.getItem("collapse_menu");
    var fixedsidebar = localStorage.getItem("fixedsidebar");
    var fixednavbar = localStorage.getItem("fixednavbar");
    var fixednavbar2 = localStorage.getItem("fixednavbar2");
    var boxedlayout = localStorage.getItem("boxedlayout");
    var fixedfooter = localStorage.getItem("fixedfooter");

    if (collapse == 'on'){
        $('#collapsemenu').prop('checked','checked')
    }
    if (fixedsidebar == 'on'){
        $('#fixedsidebar').prop('checked','checked')
    }
    if (fixednavbar == 'on'){
        $('#fixednavbar').prop('checked','checked')
    }
    if (fixednavbar2 == 'on'){
        $('#fixednavbar2').prop('checked','checked')
    }
    if (boxedlayout == 'on'){
        $('#boxedlayout').prop('checked','checked')
    }
    if (fixedfooter == 'on') {
        $('#fixedfooter').prop('checked','checked')
    }
}

</script>

<% end %>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-info " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom"  action="<%= search_index_path %>" method="get">
                <div class="form-group">
                      <input type="text" placeholder="Search patient record..." class="form-control" name="search[query_strings]" value=""/>
                </div>
            </form>
        </div>

      <ul class="nav navbar-top-links navbar-right">
        <li>
          <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">Welcome to <%= app_settings.body["app_name"] %></span>
        </li>

        <li>
          <a href="" class="btn-signout" >
            <i class="fa fa-sign-out"></i> Log out
          </a>
        </li>
      </ul>
</nav>
</div>

app/views/layouts/_topnavbar_2.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <i class="fa fa-reorder"></i>
        </button>
        <a href="#" class="navbar-brand">Inspinia</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav">
            <li class="active">
                <a aria-expanded="false" role="button" href="<%= url_for :controller => 'layoutsoptions', :action => 'index' %>"> Back to main Layout page</a>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>

    </ul>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <a href="#">
                <i class="fa fa-sign-out"></i> Log out
            </a>
        </li>
    </ul>
</div>
        </nav>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= app_settings.body["app_name"] %></title>
    <%= csrf_meta_tag %>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag "#{params[:controller] + '_' + params[:action]}" if ::Rails.application.assets.find_asset("#{params[:controller] + '_' + params[:action]}.css") %>
    <!-- Main css styles -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    

</head>
<body>
<!-- Skin configuration box -->
<!-- <%= render 'layouts/skinconfig' %> -->

    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

        <!-- Right sidebar -->
        <%= render 'layouts/rightsidebar' %>

    </div>
    <!-- End wrapper-->
    
    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag "#{ params[:controller] + '_' + params[:action]}", 'data-turbolinks-track' => true %>
    
    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

        <script type="text/javascript">

          $('.btn-signout').click(function () {
            $.ajax({
              type: "DELETE",
              url: "/signout",
              beforeSend: function(xhr) {
                var token = $('meta[name="csrf-token"]').attr('content');
                if (token) xhr.setRequestHeader('X-CSRF-Token', token);
              },
              success: function (data) {
                location.reload();
              },
              error: function (data) {
                console.log('Failed: ' + JSON.stringify(data));
              }
            });
          });

        </script>

    <%= flash_notifications -%>


</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= app_settings.body["app_name"] %></title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body class="gray-bg">

<!-- Main view  -->
<%= yield %>

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>